### ISSUE TITLE
On analysis folder

### ISSUE THREAD

**Issue by LasDes** [gipert/mugraphy#5]
Any reason in particular why only, for x angle and y angle the formulas:
```
ang_x = np.tan(theta) * np.cos(phi)
ang_y = np.tan(theta) * np.sin(phi)
```
Why not use only  atan (deltaX/deltaY) ?

**Comment by gipert** [comment]
Well, no, it is indeed the same thing. You can verify whether you get the same results.

**Comment by LasDes** [comment]
Oh I see, I get the same result.
